definitions:
  database.ApplicationForCall:
    properties:
      date:
        type: integer
      id:
        type: integer
      name:
        type: string
      phoneNumber:
        type: string
    required:
    - name
    - phoneNumber
    type: object
  database.Service:
    properties:
      id:
        type: integer
      name:
        type: string
      price:
        type: integer
    required:
    - name
    - price
    type: object
  database.TrustedTelegramUsers:
    properties:
      id:
        type: integer
      telegramID:
        type: string
    type: object
  database.User:
    properties:
      id:
        type: integer
      name:
        type: string
      password:
        type: string
    required:
    - name
    - password
    type: object
  handler.error:
    properties:
      message:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a service center API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Service Center API
  version: "1.0"
paths:
  /api/admin/cms/services:
    get:
      consumes:
      - application/json
      description: Получить актуальный список услуг с прайс-листом
      operationId: get-service
      produces:
      - application/json
      responses:
        "200":
          description: Массив информации об услугах
          schema:
            items:
              $ref: '#/definitions/database.Service'
            type: array
      security:
      - ApiKeyAuth: []
      summary: Получить список услуг
      tags:
      - cms/services
    post:
      consumes:
      - application/json
      description: Создать услугу
      operationId: create-service
      parameters:
      - description: Информация об услуге
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/database.Service'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.error'
      security:
      - ApiKeyAuth: []
      summary: Добавить услугу
      tags:
      - cms/services
  /api/admin/cms/services/{id}:
    delete:
      consumes:
      - application/json
      description: Удалить информацию об услуге
      operationId: delete-service
      parameters:
      - description: ID услуги
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.error'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handler.error'
      security:
      - ApiKeyAuth: []
      summary: Удалить услугу
      tags:
      - cms/services
    put:
      consumes:
      - application/json
      description: Обновить информацию об услуге
      operationId: update-service
      parameters:
      - description: ID услуги
        in: path
        name: id
        required: true
        type: integer
      - description: Информация об услуге
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/database.Service'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.error'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handler.error'
      security:
      - ApiKeyAuth: []
      summary: Обновить информацию об услуге
      tags:
      - cms/services
  /api/admin/task-count/paged/count:
    get:
      consumes:
      - application/json
      description: Получить общее количество задач
      produces:
      - application/json
      responses:
        "200":
          description: Количество задач
          schema:
            additionalProperties:
              type: integer
            type: object
      security:
      - ApiKeyAuth: []
      summary: Получить количество задач
      tags:
      - tasks
  /api/admin/tasks-manage:
    get:
      consumes:
      - application/json
      description: Получить список всех задач
      operationId: get-tasks
      produces:
      - application/json
      responses:
        "200":
          description: Массив информации о задачах
          schema:
            items:
              $ref: '#/definitions/database.ApplicationForCall'
            type: array
      security:
      - ApiKeyAuth: []
      - ApiKeyAuth: []
      summary: Получить все задачи
      tags:
      - tasks
  /api/admin/tasks-manage/{id}:
    delete:
      consumes:
      - application/json
      description: Удалить задачу по ID
      operationId: delete-task
      parameters:
      - description: ID задачи
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.error'
      security:
      - ApiKeyAuth: []
      summary: Удалить задачу
      tags:
      - tasks
    put:
      consumes:
      - application/json
      description: Обновить статус задачи по ID
      operationId: update-task-status
      parameters:
      - description: ID задачи
        in: path
        name: id
        required: true
        type: integer
      - description: Информация о задаче
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/database.ApplicationForCall'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.error'
      security:
      - ApiKeyAuth: []
      summary: Обновить статус задачи
      tags:
      - tasks
  /api/admin/tasks-manage/paged/pagedTasks:
    get:
      consumes:
      - application/json
      description: Получить список задач с использованием пагинации на основе параметров
        страницы и лимита
      parameters:
      - description: Номер страницы (по умолчанию 1)
        in: query
        name: page
        type: string
      - description: Лимит элементов на странице (по умолчанию 10)
        in: query
        name: limit
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Массив информации о задачах
          schema:
            items:
              $ref: '#/definitions/database.ApplicationForCall'
            type: array
        "400":
          description: Ошибка при неверном параметре
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - ApiKeyAuth: []
      summary: Получить задачи с пагинацией
      tags:
      - tasks
  /api/admin/telegram-trust:
    get:
      consumes:
      - application/json
      description: Получить список всех доверенных чатов Telegram
      operationId: get-telegram-trust
      produces:
      - application/json
      responses:
        "200":
          description: Массив информации о доверенных чатах Telegram
          schema:
            items:
              $ref: '#/definitions/database.TrustedTelegramUsers'
            type: array
      security:
      - ApiKeyAuth: []
      summary: Получить список доверенных чатов Telegram
      tags:
      - telegram-trust
    post:
      consumes:
      - application/json
      description: Создать новую запись о доверенном чате Telegram
      operationId: add-telegram-trust
      parameters:
      - description: Информация о доверенном чате Telegram
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/database.TrustedTelegramUsers'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.error'
      security:
      - ApiKeyAuth: []
      summary: Добавить доверенный чат Telegram
      tags:
      - telegram-trust
  /api/admin/telegram-trust/{id}:
    delete:
      consumes:
      - application/json
      description: Удалить информацию о доверенном чате Telegram
      operationId: delete-telegram-trust
      parameters:
      - description: ID доверенного чата Telegram
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.error'
      security:
      - ApiKeyAuth: []
      summary: Удалить доверенный чат Telegram
      tags:
      - telegram-trust
    put:
      consumes:
      - application/json
      description: Обновить информацию о доверенном чате Telegram
      operationId: update-telegram-trust
      parameters:
      - description: ID доверенного чата Telegram
        in: path
        name: id
        required: true
        type: integer
      - description: Информация о доверенном чате Telegram
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/database.TrustedTelegramUsers'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.error'
      security:
      - ApiKeyAuth: []
      summary: Обновить информацию о доверенном чате Telegram
      tags:
      - telegram-trust
  /api/task:
    post:
      consumes:
      - application/json
      description: Создать новую задачу
      operationId: add-task
      parameters:
      - description: Информация о заявке
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/database.ApplicationForCall'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.error'
      summary: Добавить задачу
      tags:
      - tasks
  /api/task/{phoneNumber}:
    get:
      consumes:
      - application/json
      description: Получить информацию о задаче по номеру телефона
      operationId: get-task
      parameters:
      - description: Номер телефона
        in: path
        name: phoneNumber
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Массив информации о заявках
          schema:
            items:
              $ref: '#/definitions/database.ApplicationForCall'
            type: array
      summary: Получить задачу
      tags:
      - tasks
  /auth/admin/sign-in:
    post:
      consumes:
      - application/json
      description: Создает аккаунт
      operationId: create-account
      parameters:
      - description: Информация об аккаунте
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/database.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.error'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handler.error'
      summary: Авторизация в CMS
      tags:
      - auth
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Author
    type: apiKey
swagger: "2.0"
